# Generated by Django 3.1.2 on 2020-11-01 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100, verbose_name='Language_name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ('language_name',),
            },
        ),
        migrations.CreateModel(
            name='LanguageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Pre-Intermediate'), (3, 'Intermediate'), (4, 'Upper-Intermediate'), (5, 'Advanced'), (6, 'Proficiency')], verbose_name='language_level')),
            ],
            options={
                'verbose_name': 'Language level',
                'verbose_name_plural': 'Language levels',
                'ordering': ('language_level',),
            },
        ),
        migrations.CreateModel(
            name='LanguageWithLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_profile.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_profile.languagelevel')),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Patronymic')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date_of_birth')),
                ('status', models.IntegerField(default=1, verbose_name='Status')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date_added')),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Profile_img')),
                ('about_myself', models.TextField(blank=True, null=True, verbose_name='About_myself')),
                ('interests', models.TextField(blank=True, null=True, verbose_name='Interests')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Skills')),
                ('languages', models.ManyToManyField(through='social_profile.LanguageWithLevel', to='social_profile.Language', verbose_name='Language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social profile',
                'verbose_name_plural': 'Social profiles',
                'ordering': ('last_name',),
            },
        ),
        migrations.AddField(
            model_name='languagewithlevel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_profile.socialprofile'),
        ),
    ]
