# Generated by Django 3.1.2 on 2020-11-01 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255, verbose_name='Institution name')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institution',
                'ordering': ('institution_name',),
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.CharField(max_length=255, verbose_name='Vacancy')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Date added')),
                ('who_added', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ('vacancy',),
            },
        ),
    ]
