# Generated by Django 3.1.2 on 2020-11-01 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20201101_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution', verbose_name='Institution'),
        ),
    ]
